### ISSUE TITLE
Exception on invalid range

### ISSUE THREAD

**Issue by tucotuco** [eightysteele/Spatial-Data-Library#44]
If the intervals dictionary in None due to an invalid range (e.g., gte == lt), api.py thows an exception as below. Need to trap this situation and return an invalid query range response.

Traceback (most recent call last):
  File "/Users/tuco/dev/google_appengine/google/appengine/ext/webapp/_webapp25.py", line 701, in __call__
    handler.get(*groups)
  File "/Users/tuco/Projects/Spatial-Data-Library/app/api.py", line 475, in get
    return self.post()
  File "/Users/tuco/Projects/Spatial-Data-Library/app/api.py", line 642, in post
    self.range_query(ranges, limit, offset) #gte, lt, variable, limit, offset)
  File "/Users/tuco/Projects/Spatial-Data-Library/app/api.py", line 572, in range_query
    for index,value in intervals.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'

**Comment by tucotuco** [comment]
Or return an empty list.

**Comment by eightysteele** [comment]
> Or return an empty list.

Yup, but empty dictionary, not list maybe?

**Comment by tucotuco** [comment]
Fixed in @3646869

**Comment by tucotuco** [comment]
Still need to trap this condition in api.py so that a malformed query such as the following is not created.

 CellIndex.query(AND(OR)))
